### ISSUE TITLE
How to perform declension of a date in Russian?

### ISSUE THREAD

**Issue by naneri** [jenssegers/date#119]
I am using the ->format() method to output the date in Russian language. But what I need is to perform declension at first. Because without it the date looks like this: "9 Март 2015", which is wrong according to Russian grammar. It is supposed to be "9 Марта 2015".

**Comment by jenssegers** [comment]
That's a difficult one. We can probably solve this using the symfony translator.

**Comment by jenssegers** [comment]
I was able to fix this issue. But I need some help from you translation the other values. According to the symfony translator there should be 3 possible choices eg. `'march'     => 'март|Марта|Марта',`, is that correct?

**Comment by jenssegers** [comment]
The rule inside the translator is this one:

```
return (($number % 10 == 1) && ($number % 100 != 11)) ? 0 : ((($number % 10 >= 2) && ($number % 10 <= 4) && (($number % 100 < 10) || ($number % 100 >= 20))) ? 1 : 2);
```

**Comment by naneri** [comment]
The declension is quite complicated. There are two main values (like "март|Марта", "январь|Января") but there are more possible values ("март|марта|марту|март|мартом|марте"), but most of those are not used when displaying the date. 
Concerning the rule that you have written - that is related to singular and plural form, not to declension. 
"марта" is used instead of "март" because it stays after the number 9. It is like in English - you can't say "Nine March 2015" you have to say "Ninth OF March 2015" and in russian we use declension ending instead of "OF" word.

**Comment by jenssegers** [comment]
Damn, so we can't use the Symfony translator logic then?

**Comment by naneri** [comment]
If it is related to singular and plural forms - then  no :(

**Comment by jenssegers** [comment]
Would it be possible to express this rule in a format like this? (https://github.com/symfony/symfony/issues/8698)

```
'{0} нет яблок|{1} есть одно яблоко|[2,4] есть %count% яблока|[5,Inf] есть %count% яблок'
```

**Comment by naneri** [comment]
You see - the only rule is why you have to put "Марта" instead of "Март" is because it is staying after 9. Same as in English. There is no difference which date it is. The rule above is also related to counting (but this time to fractions on the contrary to plural/singular forms).

**Comment by jenssegers** [comment]
Ah okay. Is it only for a single digit 9, or are there other exceptions as well?

**Comment by jenssegers** [comment]
If it is only for a single 9, this should work I think:

```
[0,9[март|[9,9]мартa|]9,Inf]март
```

**Comment by naneri** [comment]
No - i mean the declension goes, because word "Марта" stays behind a digit, no matter what digit it is. If it was not a date like in English "My favorite month is March" - "Мой любимый месяц - Март" there would be no declension. But because in a date - it is always "Марта" no matter, what number it stays after (0-10000000) same as in English, you say "First of March", "Tenth of March", "Twenty six of March", no matter which number it stays after - you have to add "of" , same here you have to use "Марта" in a date.

**Comment by jenssegers** [comment]
Oh wow, I completely misunderstood you. This is going to be quite difficult to support using the Symfony translator. Maybe something like `[0]март|],Inf]мартa` would be a possibility.

**Comment by naneri** [comment]
It should be, because dates are only positive integers. Should I prepare a list of declensed monthes?

**Comment by jenssegers** [comment]
Could you double check this unit test for me?

```
        $date = new Date('march 2015');
        $this->assertSame('март 2015', $date->format('F Y'));

        $date = new Date('10 march 2015');
        $this->assertSame('10 мартa 2015', $date->format('j F Y'));
```

**Comment by naneri** [comment]
Right now I am unable - I can perform the check on Monday, when I will be at work. Is that ok?

**Comment by jenssegers** [comment]
Sure, its just the 2 assertions that you need to double check for me. You don't have to run the unit tests itself. My current changes allow months to be specified like this:

    'march'     => '{0}март|{1}мартa',

If you have any spare time and wish to make a PR, that would be of great help!

**Comment by jenssegers** [comment]
@naneri Could you help our fixing the other month values? https://github.com/jenssegers/laravel-date/commit/873746b91bfa73c56bb445825cba1084fe84acd6

**Comment by naneri** [comment]
@jenssegers I have sent a comment to the commit

**Comment by naneri** [comment]
i could not update via composer to the latest version so I added the russian language manually and get messages like "1 {0}май|{1}мая 2015" instead of the real date :(

**Comment by logical-and** [comment]
Any progress on that?

**Comment by ipitchkhadze** [comment]
I have find a workaroud for:

> i could not update via composer to the latest version so I added the russian language manually and get messages like "1 {0}май|{1}мая 2015" instead of the real date :(

you can replace line 253
` $shortTranslated = $lang->trans($toTranslate);`

to this

`if ($key === 'May' && $this->getLocale() === 'ru') {
                        $shortTranslated = $lang->transChoice($toTranslate, 1);
                    } else {
                        $shortTranslated = $lang->trans($toTranslate);
                    }`
