### ISSUE TITLE
Doesn't show translations for timestamps retrieved from database

### ISSUE THREAD

**Issue by LoveAndHappiness** [jenssegers/date#123]
How exactly is laravel-date supposed to work here? I don't seem to get the correct translations in from the database retrieved timestamps.

```
<?php
        use Jenssegers\Date\Date;
	// This returns 'vor 0 Sekunden' in German, which I do want.
	echo Date::now()->diffForHumans();
	echo '<br/>';
	// This returns '1 day ago'. It is in English, but I need it in German.
	echo $orders->find(1)->created_at->diffForHumans();
?>
```

I opened the case also here: http://stackoverflow.com/questions/29659683/laravel-5-jenssegers-laravel-date-doesnt-show-correct-translation-how-do-i-us

because I didn't found a tag for this package in stackoverflow, I also openend this issue here, so that I get your attention on this topic.

Thank you in advance.

**Comment by The-Hasanov** [comment]
http://laravel.io/bin/bEW3X

**Comment by LoveAndHappiness** [comment]
Where do I put this file?

**Comment by The-Hasanov** [comment]
change your model this example

**Comment by LoveAndHappiness** [comment]
Which model? Order Model I suggest, (or every model where I am going to retrieve timestamps)?

**Comment by Propaganistas** [comment]
Yes, in every model where you're going to retrieve timestamps. Basically the `freshTimestamps()` and `asDateTime()` methods are overriding the default Eloquent methods with nearly identical code. The only difference is `Carbon` being swapped out for `Date`.

**Comment by EmilioBravo** [comment]
@LoveAndHappiness check this #144
