### ISSUE TITLE
Date::parse() bug

### ISSUE THREAD

**Issue by drauta** [jenssegers/date#124]
Date::parse() accepts timestamps, Carbon doen't. 
This is cool but the timezone is wrong, always is "+00:00", you can simply use Date::createFromTimestamp() and all works as expected but this made me crazy for a while...

Thankyou!!

**Comment by egorsmkv** [comment]
:+1:

**Comment by jenssegers** [comment]
Even if you pass the timezone?

**Comment by jenssegers** [comment]
Can you check if my last commit on master fixes that? :)

**Comment by egorsmkv** [comment]
Thank you! Now there is no problem.

**Comment by jenssegers** [comment]
Done!
