### ISSUE TITLE
Add 'around' for diffForHuman()

### ISSUE THREAD

**Issue by asivaneswaran** [jenssegers/date#142]
Hi,

I think it would be a good idea to add the word 'about'  for the ago sentences. So it could say:
About 2 months ago. Instead of just saying 2 months ago. Technically it's not 2 months ago day to day...

**Comment by tintamarre** [comment]
An other idea would be to change how it is rounded.

`diffForHuman()` currently works like this:
```php
Date::parse('2015-06-23 00:00:00')->diffForHumans() // 1 week ago [7 days from now]
Date::parse('2015-06-17 00:00:00')->diffForHumans() // 1 week ago [13 days from now]
```
I think it's more relevant if we round it to the higher unit if it is superior to .5 (ie: more than 1,5 weeks should render 2 weeks).

Moreover, I think that if the unit of time (days/weeks/months/year) is less than 2 (or 3), it is better to render it in the inferior unit. For example:
```php
Date::parse('2015-06-29 00:00:00')->diffForHumans() // 36 hours ago
Date::parse('2015-06-23 00:00:00')->diffForHumans() // 7 days ago
Date::parse('2015-06-17 00:00:00')->diffForHumans() // 13 days ago
Date::parse('2015-06-16 00:00:00')->diffForHumans() // 2 weeks ago
```

**Comment by asivaneswaran** [comment]
Yeah I agree with both of the ideas as well. On another thing I would do is to show the exact date if it's over year. For example:
```
Date::parse('2014-06-30 00:00:00')->diffForHumans() // 1 year ago
Date::parse('2014-01-01 00:00:00')->diffForHumans() // January 1st 2014
```

**Comment by jenssegers** [comment]
This would break "compatibility" with Carbon though.

**Comment by tintamarre** [comment]
For your information, this will probably be merged: https://github.com/briannesbitt/Carbon/pull/772/commits

**Comment by tintamarre** [comment]
The previous Carbon pull request has been accepted.

**Comment by kylekatarnls** [comment]
Regarding all the options `diffForHuman()` now has, adding 'around' would not be relevant. This issue should be closed.
