### ISSUE TITLE
Can't run in php 5.4

### ISSUE THREAD

**Issue by ridwanskaterock** [jenssegers/date#178]
app requirement :   "php": ">=5.3.3" 
Why can't run in PHP 5.4 ? 
error in config app.php line : Jenssegers\Date\Date::class
any way ?
i used library in laravel 4

**Comment by GrahamCampbell** [comment]
4.4 or 5.4?

**Comment by GrahamCampbell** [comment]
This is not a bug.

**Comment by GrahamCampbell** [comment]
> error in config app.php line : Jenssegers\Date\Date::class

That is your own code, NOT this project. You, youself have written syntax incompatible with php 5.4.

**Comment by GrahamCampbell** [comment]
Instead of `'Date' => Jenssegers\Date\Date::class,`, write `'Date' => 'Jenssegers\Date\Date',`.

**Comment by ridwanskaterock** [comment]
okay it's work, you may have to add on Readme, because for the Facade are described only runs on laravel> 4, not to laravel 4 having a minimum php version 4.4.
Thanks

**Comment by ridwanskaterock** [comment]
sorry I mean php 5.4 not 4.4 :)

**Comment by GrahamCampbell** [comment]
> because for the Facade are described only runs on laravel> 4

No, it works on ALL Laravel versions. Just, PHP 5.5+.

**Comment by danhunsaker** [comment]
Might be good to update the README to clarify that the `::class` notation isn't valid until PHP 5.5...  Can submit a PR for this purpose if desired.

**Comment by kylekatarnls** [comment]
For the record jenssegers/date 4.0.0 requires:
PHP 7.1.8+
Laravel 5.8.0+
