### ISSUE TITLE
Date::parse - Use timezone from Laravel config

### ISSUE THREAD

**Issue by rogierverbrugge** [jenssegers/date#193]
It would be a good idea to use the timezone from the Laravel config by default to parse a date.

``` php
Date::parse('2016-02-15T08:04:19.0Z');
```

So that this function should return the date in the timezone set in the config.

**Comment by jenssegers** [comment]
As far as I know there is not global setTimezone available for Carbon. Will probably have to introduce a `setDefaultTimezone` method which is then called by the service provider.

**Comment by danhunsaker** [comment]
Parsing a date string with a timezone in it will always return a DateTime (or by extension, Carbon or Date) in that timezone.  In this example, the Z at the end of the date string refers to the "Zulu" time zone, which is UTC, so this date will always parse into UTC.  You'll have to change the timezone manually in your code even with a default timezone set.

**Comment by dmarklund** [comment]
@jenssegers Is there any progress on this?

**Comment by techatmosphere** [comment]
> up

**Comment by techatmosphere** [comment]
up

**Comment by kylekatarnls** [comment]
@jenssegers should be closed IMO, forcing a timezone when the date ends with `Z` is the opposite of what it means, it would break the internet 😄 and default timezone in Laravel should be UTC too! Here is why: https://medium.com/@kylekatarnls/always-use-utc-dates-and-times-8a8200ca3164

And here is how I recommend to handle timezone with Carbon (and so jenssegers/date that extends it): https://medium.com/@kylekatarnls/handle-dates-the-right-way-in-php-c215650fc4fa
