### ISSUE TITLE
Norway has two languages

### ISSUE THREAD

**Issue by piperone** [jenssegers/date#209]
The 'no'-identifier refers to the macrolanguage norwegian, however, there are two official languages in Norway: Norwegian Bokmål (nb) and Norwegian Nynorsk (nn). The translation you have in your repo is for Norwegian Bokmål and should be named 'nb'.

**Comment by dasgarner** [comment]
Im running into this issue too - is there any reason why `no.php` couldn't be duplicated to `nb.php` ?
