### ISSUE TITLE
How to present a date based on locale?

### ISSUE THREAD

**Issue by deleugpn** [jenssegers/date#212]
I thought this was the sole purpose of this package, but it looks like my assumption was wrong because I cannot find it at all.

Here is my goal:

```
        Date::setLocale('pt-BR');
        dd(Date::today()->toDateString());
```

This would dump **30/06/2016** because that's the brazillian default date format.

```
        Date::setLocale('en');
        dd(Date::today()->toDateString());
```

This would dump **6/30/16** because that's the US default date format.

I'm using `->toDateString()` here just as an example, it doesn't have to be that method precisely, it just have to be a method that doesn't require the format, because I don't want my controller having a specific-language format. Not to mention that if I wanted to provide the format, I could just use php's native function `date()`. 

Anyway, the tl;dr is: How do I get a Date to be automatically formatted by the Locale that has been set without having to specify the format?

Thank you.

**Comment by danhunsaker** [comment]
You're describing `strftime('%x', $date)` here...

**Comment by Deleugpn** [comment]
The goal is not to rely on server locale settings (which most likely will be en-US). The goal is to rely on Laravel's runtime locale.

**Comment by danhunsaker** [comment]
It would be more accurate to say this library supports date translation than date localization.  But.  I don't think it would be terribly difficult to add support for localizing as well.

Proposal
--------
- Three new methods: `::localDate()`, `::localTime()`, and `::localDateTime()`.
- Three new language file entries: `format_date`, `format_time`, and `format_datetime`.
- Each new function pulls the associated format string from the language file, and passes it to the existing formatting method(s), returning the result.

This may be further expanded with long and short formats as well, if desired.

Thoughts?

**Comment by Deleugpn** [comment]
Looks pretty decent and not so hard to achieve. Since the package already have the ability to format date and time as you want, those three methods would be pretty small and basically a shortcut to the desired behavior.

**Comment by deleugpn** [comment]
Still desiring this. I was just doing some Google Search on this subject again and found my own thread :D

**Comment by danhunsaker** [comment]
Reinvestigating the current code more closely, it should be fairly simple to extend the existing formatting options to support locale-aware formatting, simply by calling `parent::setToStringFormat($localeStrings['format_datetime'])` in `static::setLocale()`, and using it as the default format anywhere a format argument is expected...  The above-suggested methods could still be added, though I think I'll adjust the names for consistency.

Does this sound like a good approach, or is it too sweeping a change?

**Comment by danhunsaker** [comment]
The first half of this is submitted as PR #236; the other half, about defaulting to `format_datetime` everywhere a `$format` is expected, I've decided to hold off on until I get further feedback on it.
