### ISSUE TITLE
DateTime::__construct(): Failed to parse time string with MongoDb

### ISSUE THREAD

**Issue by ctf0** [jenssegers/date#225]
am having an app that use mysql which all works simply perfect & without a hitch , however am trying to migrate from mysql to mongodb using https://moloquent.github.io/master/#moloquent , so the code as follow

- route

```php
Route::group([
    'prefix'     => LaravelLocalization::setLocale(),
    'middleware' => ['localeSessionRedirect', 'localizationRedirect'],
    ], function () {

        Date::setLocale(App::getLocale());

       // routes
    }
);
```

- model

```php
public function getCreatedAtAttribute($value)
{
    return Date::parse($value)->format('F d, Y');
}
```

- mongo collection
```json
"updated_at" : ISODate("2016-10-19T14:08:27.624Z"),
"created_at" : ISODate("2016-10-19T14:08:27.624Z"),
```

![test](https://cloud.githubusercontent.com/assets/7388088/19524120/facb08f0-961c-11e6-909f-05d5898a41dd.jpg)

**Comment by danhunsaker** [comment]
You're attempting to parse a timestamp.  That's not likely to work.  Either prefix it with an `@`, or use the timestamp-handling methods instead,

**Comment by ctf0** [comment]
can u plz tell me why it was working on mysql but not on mongo ? is it because of the field type or am am i suppose to use special method for mongo ?

**Comment by danhunsaker** [comment]
Because MySQL stored dates as strings that needed parsing, while Mongo stores them as timestamps, which are just the (integer) number of seconds since 1970-01-01 00:00:00 UTC.

**Comment by ctf0** [comment]
oh okay, so to get the above to work it should be 
```php
Date::parse(@$value)->format('F d, Y');
```
 ???

**Comment by danhunsaker** [comment]
`Date::parse("@{$value}")->format('F d, Y');`

**Comment by ctf0** [comment]
sweet, one last question, i also have things like
```php
Carbon::parse($this->created_at)->toFormattedDateString();
Carbon::now()->addMonth($value)
```

it should also be as above
```php
Carbon::parse("@{$this->created_at}")->toFormattedDateString();
Carbon::now()->addMonth("@{$value}")
```

**Comment by danhunsaker** [comment]
Pretty sure `->created_at` is going to be your formatted `Date` value, so no, those shouldn't change.

**Comment by ctf0** [comment]
many thanx @danhunsaker 🍺

**Comment by ctf0** [comment]
hi @danhunsaker , i have another issue also related to the date, not sure if i should open a new ticket for it but maybe u could help me with it

the field
```json
"created_at" : ISODate("2016-10-19T17:11:21.717Z")
```
on view
```
January 03, 48771
```
controller
```php
public function getCreatedAtAttribute($value)
{
    return Date::parse("@{$value}")->format('F d, Y');
}
```

**Comment by danhunsaker** [comment]
Looks like some of your dates are stored as timestamps, and others aren't.  I'd look into that inconsistency.

**Comment by ctf0** [comment]
perfect, tell me if you needed any further details

**Comment by ctf0** [comment]
@danhunsaker i made a little tool to migrate the data from mysql to mongo https://github.com/ctf0/MysqlToMongoDb , and i found 2 things

1- if i migrated the tables through laravel `art migrate` the field that have the date is timestamp which leed to using the `@` hack & the date being incorrectly rendered.

2- but when i migrate using my tool, the field is now string, which doesnt need the `@` + the view can now display the date correctly.

i thought this may help u.

**Comment by ctf0** [comment]
fixed on the mongo package ticket, thanx again.
