### ISSUE TITLE
Format with text

### ISSUE THREAD

**Issue by nam-co** [jenssegers/date#233]
Hi, thanks for the script it works great, I was wondering if its possible to include text in the ->format, like this: Date::parse($cv->created_at)->format('l  of j F Y') will create " friday 30 of december 2016", is there a way to do this?

Also, is there a way to make words first character capital letters? like Friday 30 of December 2016

Appreciate the help
thanks

**Comment by cmontezano** [comment]
The way to do this is escaping every character you want to insert in format
```
Date::parse($cv->created_at)->format('l \o\f j F Y')
```
This way you'll achieve the expected result.

**Comment by nam-co** [comment]
Thanks
