### ISSUE TITLE
yesterday issue

### ISSUE THREAD

**Issue by mostafa6765** [jenssegers/date#250]
```php
{{ Date::parse($me->created_at)->ago() }}
```

I want it will show as like `yesterday` then ` 2days ago` . there any way to solve this .

**Comment by kylekatarnls** [comment]
Now than jenssegers/date supports Carbon 2, you can use it to get "yesterday"/"tomorrow":
```php
Date::parse('yesterday')->diffForHumans(['options' => CarbonInterface::ONE_DAY_WORDS])
```
