### ISSUE TITLE
Duplicate keys in the localization array

### ISSUE THREAD

**Issue by ZapevalovAnton** [jenssegers/date#253]
In the file https://github.com/jenssegers/date/blob/master/src/Lang/ru.php duplicate keys. Accordingly, the plural does not work for this month. 

![image](https://user-images.githubusercontent.com/6674242/31478652-543b387e-af2b-11e7-9ce8-f8f4cedbcf63.png)

**Comment by kylekatarnls** [comment]
@jenssegers Why did you close this issue? This is a good quick fix, but this is not an acceptable long term solution. It means for every language, `may` can not be shortened. So in spannish: `mayo` would have a long form: `mayo` and a short one: `may`, but if you try to get the short form, you will get the long, or if you use the other order of keys, you will get the plural broken.

Any array in PHP should never have duplicate keys. A good solution would be distinguish keys: for example with `"jan.", "feb.", ... "may."` and so update all translations and the getter of them. If you agree, I can do it easily.

**Comment by ref** [comment]
Maybe someone fix this bug? Look at this:

![2019-02-26 13-24-21](https://user-images.githubusercontent.com/505388/53391762-f699e000-39c9-11e9-8e06-07fa6cf342ed.png)

`{{ question.created_at|date('d M. Y') }}`

**Comment by kylekatarnls** [comment]
https://github.com/jenssegers/date/pull/298 fix it but is not yet merged.
