### ISSUE TITLE
Write a version of this library on top of Chronos

### ISSUE THREAD

**Issue by Evertt** [jenssegers/date#258]
[Chronos](https://github.com/cakephp/chronos) is a replacement for Carbon which has 2 main benefits: it's made to be immutable by default and it's more performant than Carbon.

I think a lot of people are gonna switch over to Chronos for that reason. Maybe even Laravel in 6.0. And I would very much like to have an extension of Chronos that adds more localization support. Just like this repository does for Carbon.

So uh, would you be willing to create another version of this repository, one that extends Chronos?

**Comment by kylekatarnls** [comment]
Jenssegers does not extends Carbon. And Carbon is also localized. It would be a very bad idea for Laravel to replace a localized library with a less-featured library. When you get more features, you loose some performance, there is no magic trick to benefit of all. You will have to choose. A solution can be to extends yourself one of them and use traits of the other to add methods.

**Comment by kylekatarnls** [comment]
This could be closed IMO, Carbon is now strongly maintained, has a wide localization support, support immutability and many features Chronos hasn't; Laravel chose Carbon 2 over Chronos for its last release (5.8).

If features are missing in Chronos, use jenssegers/date, if features are missing in Carbon, feature requests are welcome on https://github.com/briannesbitt/Carbon/issues.

It seems now way more reasonable than re-code the whole set of localization features for Chronos.

@jenssegers maybe this could be closed unless you plan to implement a Chronos compatible version.
