### ISSUE TITLE
Manual Installation not through Composer

### ISSUE THREAD

**Issue by sameervirus** [jenssegers/date#263]
Hi,

Any way to install without composer

Best Regards
Samir

**Comment by sameervirus** [comment]
My app already running in shard hosting and haven't SSH or any thing to run composer.

**Comment by kylekatarnls** [comment]
When a composer package requires 20 dependencies and each of them could require average 10 other dependencies, you can easily have to install hundreds packages manually then handle all possible PSR autoload. Or you can just rely on composer.

You don't need SSH access for Composer, you can install composer dependencies locally, then upload the whole vendor directory.

**Comment by danhunsaker** [comment]
This ↑ would be the recommended approach, yes.

**Comment by sameervirus** [comment]
I put the required package on composer json file, then upload the package locally to vendor/jenssegers/date, then add the 'Date' => Jenssegers\Date\Date::class, to config/app.php.

in controller i use Jenssegers\Date\Date; but get Class 'Jenssegers\Date\Date' not found.

I don't have much experience so please more explain ?

**Comment by danhunsaker** [comment]
You need to upload the entire `vendor/` directory. There will be other dependencies in there, and the Composer autoloader files will have been updated as well.

**Comment by sameervirus** [comment]
@danhunsaker all dependencies already there i just upload the Date package. the app already in the server i just want to add the date package

**Comment by danhunsaker** [comment]
I get that, but Date has its own dependencies, _and_ the autoloader files are still updated any time you install a new package. So you need to upload the entire thing every time. I recommend using `rsync` for that to skip uploading files that are already in place and unchanged, but you still need to upload everything. Every time.

**Comment by sameervirus** [comment]
Got it, Thank you.
