### ISSUE TITLE
How to get a list of all the names of the days of the week?

### ISSUE THREAD

**Issue by MaxChu23** [jenssegers/date#275]
I'm wondering if there's a way of getting a full list of all the names of the days of the week or month names. It would be very helpful for creating the tables with the columns named as such depending on which language is used. Thanks!

Update: I found the solution, but it's not very clean:

`$date = Date::getTranslator()->getCatalogue()->all()['messages']; // gets a full translation array`
`$days = array_slice($date,23); // 23 is index of 'monday'`

**Comment by kylekatarnls** [comment]
With Carbon >= 2.16, an elegant way could be:

```php
var_dump(explode(',', Carbon::translateTimeString('Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday', 'en', 'fr')));
```

Or:
```php
var_dump(array_map(function ($number) {
  return Carbon::parse("next Monday + $number days")->locale('fr')->dayName;
}, range(0, 6)));
```

Replace `fr` by any language you want.
