### ISSUE TITLE
ErrorException in Date.php line 10: Declaration of Jenssegers\Date\Date::setTranslator() should be compatible with Carbon\Carbon::setTranslator

### ISSUE THREAD

**Issue by wwhitesoft** [jenssegers/date#277]
Today trough composer update i got this error. Probably because a new version of Carbon is being installed.
ErrorException in Date.php line 6: Declaration of Jenssegers\Date\Date::setTranslator() should be compatible with Carbon\Carbon::setTranslator
Someone got this exception?

**Comment by januhlavitocz** [comment]
I ran into the same problem today. It's probably because you use nesbot/carbon @ dev-master
Maybe you have minimum stability: dev in your composer.json - remove that or specifiy, that you want exactly: nesbot/carbon last stable version (1.22.1 at the moment).

**Comment by DelightedD0D** [comment]
This happened to me also. As a workaround, I added jenssengers/date to my composer.json and specified the version 3.2. Updating works as expected now


```
"require": { 
        "jenssegers/date": "^3.2", 
    },
```

**Comment by danieltamas** [comment]
Doesn't work for me

**Comment by machinecodeblue** [comment]
doesn't work for me
![image](https://user-images.githubusercontent.com/279555/36815593-35345fdc-1ca9-11e8-8bcf-beab93e41c52.png)

**Comment by luukverhoeven** [comment]
Adding: , $parts =1 to the function is the solution.

 public function diffForHumans(Carbon $since = null, $absolute = false, $short = false, $parts = 1)

**Comment by AugmentBLU** [comment]
Can you please sort this so we aren't having to manually fix files as it completely breaks auto deployments. Thanks!
