### ISSUE TITLE
Translating `S` format

### ISSUE THREAD

**Issue by darron1217** [jenssegers/date#300]
`$date->format('jS')` results `2nd`

I want to translate `nd` to my language

How can I achieve it?

**Comment by kylekatarnls** [comment]
Seems not implemented as far as I know, but you can check Carbon 2 `isoFormat` that have ordinal (`st`, `nd`, `th`, etc.) implemented and yet translated in many languages.

**Comment by vpratfr** [comment]
Same issue here in French language (date appears as `1st décembre` instead of `1er décembre`). Leaving a note here to get a note when this gets resolved.

**Comment by kylekatarnls** [comment]
With pure Carbon:
```php
Carbon::setLocale('fr');

echo Carbon::now()->startOfMonth()->isoFormat('Do MMMM');
```

`1er octobre`

I'm french, so you can safely rely on the native Carbon class to be well translated in French.

I really recommend to simply use `isoFormat` from Carbon class itself whenever possible. The way Jessengers overrides the `format` method has a drawback: some other libraries may expect `DateTimeInterface` and so call `format` relying on the fact that `DateTimeInterface::format` returns English formatted dates. But when passing Jessengers dates, it would produce unexpected results if you don't reconvert them into raw `DateTime` objects first.
