### ISSUE TITLE
[QUESTION] What is the language name of each file?

### ISSUE THREAD

**Issue by hAbd0u** [jenssegers/date#301]
Hello,
This is not an issue or some thing like that, I just need those [days translation](https://github.com/jenssegers/date/tree/master/src/Lang) but unfortunately for some files I am confused of what is the language of each file.
Can you please add at the top file the language name?

**Comment by kylekatarnls** [comment]
It's an ISO norm:
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by kylekatarnls** [comment]
Now with Carbon 2, you can get many informations about a locale (language name, native name, region, etc.) via the  `Language` class:
```php
echo (new \Carbon\Language('zh_CN'))->getIsoName();
```

**Comment by hAbd0u** [comment]
@kylekatarnls Can I query for the available languages supported using this class?
