### ISSUE TITLE
Adding Kurdish Language (cks)

### ISSUE THREAD

**Issue by HalwestRasul** [jenssegers/date#302]
hello,
this is all about the Kurdish Language:
https://en.wikipedia.org/wiki/Kurdish_languages

thanks for adding it. ♥

**Comment by kylekatarnls** [comment]
Right ISO code for Kurdish is ku (not cks): https://fr.wikipedia.org/wiki/Liste_des_codes_ISO_639-1

Then if you know Kurdish, you should submit a pull-request to add the src/Lang/ku.php file.

**Comment by HalwestRasul** [comment]
thanks, @kylekatarnls  for your response,

We have tow of most used dialects in the Kurdish language:

1. ckb: Central Kurdish (used by Kurdish people in Iraq and Iran)
2. Ku: Kurmanji (used by Kurdish people in Turkey and Syria)

and they are different from writing alphabets and speaking, so they are used on facebook, Check this:
https://developers.facebook.com/docs/messenger-platform/messenger-profile/supported-locales

ku: Kurmanji Kurdish: facebook code = ku_TR 
ckb: Central Kurdish: facebook code = cb_IQ 

and I'm from the part of Kurdistan of Iraq. that's a reason that why I asking for the ckb version of the Kurdish language. 

best regards.

**Comment by kylekatarnls** [comment]
So what you propose is in fact cb.php if I well understand.

**Comment by HalwestRasul** [comment]
that's my pull Request: https://github.com/jenssegers/date/pull/303
