### ISSUE TITLE
Use Symfony\Contracts\Translation\TranslatorInterface instead of Symfony\Component\Translation\TranslatorInterface

### ISSUE THREAD

**Issue by Roadirsh** [jenssegers/date#311]
Hi,
Just as a reminder, we will need to update the package to use the new TranslatorInterface.

The one in use is currently deprecated in Symfony 4.2. 

Symfony 4.3 is planned for May 2019.

Thank you!

**Comment by kylekatarnls** [comment]
@Roadirsh according to a discussion with Symfony staff and the versioning described in the Symfony doc, it should not disappear before the next major release (Symfony 5.0). So `"symfony/translation": "^2.7|^3.0|^4.0"` as given in the jenssegers/date composer.json is safe.

**Comment by kylekatarnls** [comment]
@Roadirsh Something funny?

**Comment by Roadirsh** [comment]
No! Just that it’s a good news.

**Comment by kylekatarnls** [comment]
Oh ok, misunerdstood the emoji :)
