### ISSUE TITLE
BUG: Russian translation of the month

### ISSUE THREAD

**Issue by nepster-web** [jenssegers/date#313]
Pay Attention, Please:
https://github.com/jenssegers/date/blob/master/src/Lang/ru.php#L30
https://github.com/jenssegers/date/blob/master/src/Lang/ru.php#L43

We really see identical array keys with different values.

This only applies to May month, for example:
```php
Date::setLocale('ru');
echo \Jenssegers\Date\Date::instance(new \DateTime('2019-05-10'))->format('M j, D H:i');
```
Result:
```{0}май|{1}мая 10, пт 00:00```

However, the correct result will be:
```май 10, пт 00:00```

**Comment by kylekatarnls** [comment]
I proposed a fix months ago and it's still open: https://github.com/jenssegers/date/pull/298

But meanwhile I released Carbon 2 with a full support of internationalization (more languages, handling of différent start of weeks, regions, interval, period, ordinal, list). So the best way could be to rely on the inherited isoFormat of Carbon 2 instead. https://carbon.nesbot.com/docs/#api-localization

Depending on what for you use **jenssegers/date** you may not need it at all and could use Carbon raw. In fact the only feature that does not have an equivalent in Carbon now is createFromFormat using day/month names with an other language that English.

**Comment by nepster-web** [comment]
Thank you, in the future I will migrate to carbon 2.

**Comment by crysan** [comment]
str_replace('{0}Май|{1}Мая', 'Май', mb_convert_case($dd->format('M Y'), MB_CASE_TITLE, "UTF-8"));
