### ISSUE TITLE
Unable to choose a translation for "1 dzień|:count dni" with locale "pl" for value "5"

### ISSUE THREAD

**Issue by supernrm** [jenssegers/date#33]
Unable to choose a translation for "1 dzień|:count dni" with locale "pl" for value "5". Double check that this translation has the correct plural options (e.g. "There is one apple|There are %count% apples")
## 

That strange because in polish we have:
1 dzień
2 dni
5 dni
1576352745 dni

so only "dzień" and "dni" but translator looking for... 5 ?

**Comment by vigneshpalanivel** [comment]
Hi, Did you solved this issue ? I'm getting this same issue.. Please share your solution..

**Comment by danhunsaker** [comment]
The error message implies that `:count` should be `%count%`...  Maybe that's the issue?
