### ISSUE TITLE
Support Laravel 7 

### ISSUE THREAD

**Issue by serderovsh** [jenssegers/date#334]
Good afternoon.
Please add support for Laravel 7

**Comment by indexcoder** [comment]
Yes, please add support for Laravel 7

**Comment by kylekatarnls** [comment]
Kind reminder: Carbon 2 available out of the box in Laravel 7 provide equivalent features for internationalization, diff, timespan, etc.

**Comment by serderovsh** [comment]
This package is already out of date.
I adapted for  "Carbon v2".

This dependence has already been ruled out.

**Comment by jenssegers** [comment]
I made a v4.0.0-beta version that you can try out.

**Comment by kylekatarnls** [comment]
I just tried to install it in a fresh Laravel 7 app and use it with some of the new languages supported (like Amharic) and I properly get `ረቡዕ` for `Date::parse('ጃንዩወሪ 1')->format('l')`

**Comment by jafarchoupan** [comment]
support laravel 7 please
my big project get very problem

**Comment by kylekatarnls** [comment]
Use v4.0.0-beta

**Comment by Askancy** [comment]
How can I install it with composer the 4.0.0-beta?

**Comment by kylekatarnls** [comment]
Use "jenssegers/date": "^4.0.0@beta"
See composer doc: https://getcomposer.org/doc/articles/versions.md#stability-constraints

**Comment by xewl** [comment]
Using the ^4.0.0@beta version worked.
Also went all-in by overriding what Laravel's Date Facade was using by adding
`\Illuminate\Support\Facades\Date::useClass(\Jenssegers\Date\Date::class);`
to the AppServiceProvider's boot() method. -> win!

**Comment by jenssegers** [comment]
Just released a non-beta version.

**Comment by kylekatarnls** [comment]
Great news. I guess this will close some of the remaining issues/PRs.
