### ISSUE TITLE
Default use in Laravel Eloquent model

### ISSUE THREAD

**Issue by ghost** [jenssegers/date#44]
Is it possible to use this library instead of Carbon as default for timestamp fields in Laravel Eloquent models?

So one could use `$post->active_at->ago()` instead of `Date::parse($post->active_at)->ago()` in a template

Thanks!

**Comment by halilim** [comment]
I think this would be nice to include in the documentation. I was assuming it would work this way until I unpleasantly recalled that `Carbon\Carbon` was hardcoded in the Laravel.

**Comment by jenssegers** [comment]
One possible solution would be to include a trait for Laravel models that returns Date instances.

**Comment by anatoliyarkhipov** [comment]
What methods should I overwrite to achive this? What I already found: `fromDateTime`, `asDateTime` and `freshTimestamp`.

**Comment by UksusoFF** [comment]
> One possible solution would be to include a trait for Laravel models that returns Date instances.
https://gist.github.com/bobbybouwmann/c912814003883955a4c1aae9dcbb97e3
