### ISSUE TITLE
Feedback: rename GitHub repo

### ISSUE THREAD

**Issue by jenssegers** [jenssegers/date#99]
I feel like I should rename the repository to `php-date` instead of `laravel-date` as it is not limited to be used with Laravel only. What do you guys think?

**Comment by jenssegers** [comment]
Or we could also call it something like 'Carbonic', or something.

**Comment by CylonSK** [comment]
I think Carbonic is better one

**Comment by kylekatarnls** [comment]
It will be a bit confusing with Carbon no? And if you don't know the repo, `php-date` is more intuitive to find in a search. Maybe something to reminds internationalization : `universal-date`.

**Comment by vinkla** [comment]
Maybe just `jenssegers/date`? It is much cleaner.

**Comment by jenssegers** [comment]
Or maybe `diem` or `tempus` (from latin)

**Comment by vinkla** [comment]
Maybe `die` shouldn't be in the word. Then I think `tempus` sounds better.
